Updates 2020
coderbyheart/open-source-meetup-alternatives pull request #12
Opened 2020-11-22 00:44 UTC by bkil

- Fix Pretix VCS URI
- Mark Thinkmill as defunct
- Add Gath (Closes #11)
- Add structr/meetdown (Closes #8)
- Add more mature or defunct ones: Friendica, Hubzilla, calsocial, Communecter, Human Connection, Upcoming

2020-11-22 13:49 UTC, coderbyheart requested changes

2020-11-22 13:49 UTC, coderbyheart commented on README.md
> +¹: _mature_ = the project is actively used by groups, _new_ = this is a new project with no usable software, _in development_ = usable software exists, but is not ready for general use, _defunct_ = w
I don't like calling an open-source project *defunct* for the fact that there haven't been commits in a year. It might still work perfectly fine. I think *in development* is a good classification for such a project, or *inactive* if it's a project which hasn't seen commits in 2+ years.

2020-11-22 13:49 UTC, coderbyheart commented on README.md
> +¹: _mature_ = the project is actively used by groups, _new_ = this is a new project with no usable software, _in development_ = usable software exists, but is not ready for general use, _defunct_ = w
Thank you for your additions!

2020-11-22 17:28 UTC, bkil commented on README.md
> +¹: _mature_ = the project is actively used by groups, _new_ = this is a new project with no usable software, _in development_ = usable software exists, but is not ready for general use, _defunct_ = w
I'm flexible in choosing the exact wording.

However, I can see two clusters of projects according to analytics charts: one that are really in development and they receive commits monthly, and ones that were being experimented with on a POC level in the beginning (especially if a project was a one man show), but its developer then lost interest. Who will want to continue such a project? If you are a developer or one into psychology, you should know that NIH and greenfield are gold.

It doesn't matter whether they lost interest 1 or 2 years ago, so I wouldn't draw a strict line, but I would definitely call `meetdown` a one time proof of concept demo as declared in its readme. Thus I wouldn't imagine anyone bringing any of their communities over there in the future (I don't think anyone has in the past either).

I would definitely not call these _in development_, although I would support _inactive_. Mobilizon is still _in development_, despite the fact that there exist dozens of instances for it already and they reached 1.0 as well. Although having that released only recently, I still wouldn't call it _mature_, but what would it take to consider it being _done_?

Also, I think I would use fewer states and simply classify whether a solution is usable or not. It doesn't matter whether the code had been missing critical features since years or only just recently - if it's missing these (or contains exploits), I'd simply just not recommend it. It's also not interesting since how long they could not deliver a working version - what I need to know is whether they already ship a reliable and functional version in production at this moment in time.

2020-11-24 08:31 UTC, merged

2020-11-24 08:37 UTC, coderbyheart commented on README.md
> +¹: _mature_ = the project is actively used by groups, _new_ = this is a new project with no usable software, _in development_ = usable software exists, but is not ready for general use, _defunct_ = w
You make some very good points. I think it could be valuable to show which meetups are using these alternatives, because this in the end will tell if a project is viable.

2020-11-24 10:58 UTC, bkil commented
Thanks for merging. And sorry for the harsh language. Feel free to improve the categorization or the wording. I view such git version controlled documents more like Wikipedia and OpenStreetMap where the more edits are made - the better.

That's unlike software where merging imperfect changes may break systems, hence we must strive for perfection at every point in that case. :smile_cat: 

You may also consider visiting fediverse protocol comparison services for an inspiration, they list the number of instances, users and activities for each alternative:
* https://the-federation.info/#protocols
* https://podupti.me/